<?php 
	$page -> addScript("js/jquery-1.8.2.js","js/jquery-ui_1.9.1.js",'js/jquery.form.js');
    if($controller->view=='views/admin/adminClients.phtml')
    {
        $page -> addScript('js/mask.js');
    }
    $page -> addScript('js/admin.js');
    $page -> addCss("css/reset.css","css/jquery-ui-1.9.1.css","css/admin.css");
?>
<table id="rez" height="100%" cellpadding="2" cellspacing="0" class="main">


			