<?php
    $db = db :: getInstance(); 
    $action = $controller -> getParam(1);
    $id = (int)$controller -> getParam(2);
    
    if ($action != 'delete' and $action != 'edit' and $action != 'add') header("Location: /admin/firm");
    
    if ($action == 'delete')
    {
        //плучаем id всех товаров которые относились к данному производителю
        $sql="SELECT * FROM products WHERE idFirm={$id}";
        $db->query($sql);
        if($db->getCount()>0)
        {
            $sql_all_pr_this_firm=$db->getArray();
            //пройдемся и удалим их из состава наборов
            foreach($sql_all_pr_this_firm as $sql_all_pr_this_firm_indexs=>$sql_all_pr_this_firm_val)
            {
                $sql_update_sostav="UPDATE sostav SET archive=1 WHERE id_ass=".$sql_all_pr_this_firm_val['id'];
                $db->query($sql_update_sostav);
            }
        }
        //обновляем товары 
        $sql="UPDATE products SET archive=1 WHERE idFirm={$id}";
        $db->query($sql);
        $db -> query("UPDATE sfirms SET archive=1 WHERE id = {$id}");
        header("Location: /admin/firm");
        exit();
    }
    if ($action == 'edit')
    {
        $db -> query("SELECT name FROM sfirms WHERE id = {$id}");
        $firm = $db -> getValue();
        if (!$firm) header("Location: /admin/firm");
    }
?>
<tr>
<td class='head'>
<?php
    $tut = 'firm';
    include "menu.php"; 
    $form = new ad();
?>
</td>
</tr>
<tr>
    <td>
    <div class="back"><a href="/admin/firm">НАЗАД</a></div>
        <div class="title"><?=($action == 'add')?'Добавление':'Редактирование';?> производителя</div>
		<?php
        ($action == 'add')?$page->setTitle('Добавление производителя | Высший сорт'):$page->setTitle('Редактирование производителя | Высший сорт');
        echo $form -> formb('form','form','post','multipart/form-data','','views/admin/ajax/firm.php','',"
        if (responseText.indexOf('error') == -1) location.href='/admin/firm';
            else
            {
                $('form#editForm input[type=file]').attr('disabled',false);
            	alert(responseText.replace(/<.*?>/g, ''));
            }");
        if($action == 'add')
        {
            $title = 'Введите нового производителя';
            $btn = 'add';
        }
        else
        {
            $title = 'Редактирование производителя';
            $btn = 'edit';
        }
            
        if ($firm and $id) echo $form->input_('hidden','id','','',$id,'',0,'','','','','','','');
        echo "<table style='width:100%;'>";
            echo "<tr><td>";
            echo $form -> titleandhelp($title,'','text-align:left');
            echo "</td><td>";
            echo $form->input_('text','name','','',$firm,'width:350px;float:left;','',0,'','','','','','','');
            echo "</td></tr>";
            echo "<tr><td colspan='2' align='center'><br />";
            echo $form->input_('submit',$btn,$btn,'','Сохранить','',0,'','','','','','','');
            echo "</td></tr>";
        echo "</table>";
        echo $form->forme();
        ?>
    </td>
  </tr>