<tr>
<td class='head'>
<?php
    $tut = 'subgroup';
    include "menu.php"; 
    $db = db :: getInstance();   
    $form = new ad(); // Создаем экземпляр класса Sample
?>
</td>
</tr>
<tr>
    <td>
        <div class="title">Виды продукции</div>
		<?php
        echo $form -> formb('form','form','post','multipart/form-data','','','','');
        $page->setTitle('Вид продукции | Высший сорт');
        echo '<a href="/admin/subgroupEditor/addsubgroup">+ ДОБАВИТЬ ВИД ПРОДУКЦИИ</a>';
        $db -> query("SELECT name,id FROM ssubgroups ORDER BY name ASC");
        $count = $db -> getCount();
        //$half = floor($count/2);
        if ($count > 0) 
        {
            $groups = $db -> getArray();
            echo '<ul>';
            foreach($groups as $i => $group)
            {                
                echo '<li style="text-align:left">';
                echo $group['name'];
                echo '&emsp;<a href="/admin/subgroupEditor/editsubgroup/'.$group['id'].'"><img src="/img/admin/e.png" title="Редактировать"/></a>';
                echo '&emsp;<a class="delsubgroup" href="/admin/subgroupEditor/deletesubgroup/'.$group['id'].'"><img src="/img/admin/d.png" title="Удалить"/></a>';
                echo'</li>';
            }
            echo '</ul>';
        }
        echo "<table style='width:100%;'>";
        echo "</table>";
        echo $form->forme();
        ?>
    </td>
  </tr>