<?php
    $db = db :: getInstance(); 
    $action = $controller -> getParam(1);
    $id = (int)$controller -> getParam(2);
    $subaction = $controller -> getParam(3);
    $subid = (int)$controller -> getParam(4);
    
    //if ($action != 'deletegroup' and $action != 'editgroup' and $action != 'addgroup') header("Location: /admin/subgroup");
    //if ($action != $subaction)
    //if ($subaction != 'deletesubgroup' and $subaction != 'editsubgroup' and $subaction != 'addsubgroup') header("Location: /admin/subgroup");
    
    if($action == 'addsubgroup')
    {
        $title = 'Введите название нового вида продукции';
        $btn = 'add';
    }
    else
    {
        $title = 'Редактирование вида продукции';
        $btn = 'edit';
    }
    
    if ($action == 'deletesubgroup')
    {
        //плучаем id всех товаров которые относились к данной категории продкуции
        $sql="SELECT * FROM products WHERE idSubgroup={$id}";
        $db->query($sql);
        if($db->getCount()>0)
        {
            $sql_all_pr_this_firm=$db->getArray();
            //пройдемся и удалим их из состава наборов
            foreach($sql_all_pr_this_firm as $sql_all_pr_this_firm_indexs=>$sql_all_pr_this_firm_val)
            {
                $sql_update_sostav="UPDATE sostav SET archive=1 WHERE id_ass=".$sql_all_pr_this_firm_val['id'];
                $db->query($sql_update_sostav);
            }
        }
        //обновляем товары 
        $sql="UPDATE products SET archive=1 WHERE idSubgroup={$id}";
        $db->query($sql);
        $db -> query("UPDATE ssubgroups SET archive=1 WHERE id = {$id}");
        header("Location: /admin/subgroup");
        exit();
    }

    if ($action == 'editsubgroup')
    {
        $db -> query("SELECT name FROM ssubgroups WHERE id = {$id}");
        $group = $db -> getValue();
        if (!$group) header("Location: /admin/subgroup");
    }
?>
<tr>
<td class='head'>
<?php
    $tut = 'subgroup';
    include "menu.php"; 
    $form = new ad();
?>
</td>
</tr>
<tr>
    <td>
        <div class="back"><a href="/admin/subgroup">НАЗАД</a></div>
        <?php 
             if($action == 'addsubgroup')
             {
                print "<div class='title'>Добавление вида продукции:</div>";
                $page->setTitle('Добавление вида продукции | Высший сорт');
             }
             else
             {
                print "<div class='title'>Изменение вида продукции: ".$group."</div>";
                $page->setTitle('Изменение вида продукции | Высший сорт');
             }
        ?>
        
		<?php
        
        if($action == 'addsubgroup')
        {
            $title = 'Введите название нового вида продукции';
            $btn = 'addsubgroup';
        }
        else
        {
            $title = 'Изменить имя вида продукции';
            $btn = 'editsubgroup';
        }
        echo $form -> formb('form','form','post','multipart/form-data','','views/admin/ajax/subgroup.php','console.log(jqForm);',"
        if (responseText.indexOf('error') == -1) 
            location.href='/admin/subgroupEditor/editsubgroup/'+responseText;
        else
       	    alert(responseText.replace(/<.*?>/g, ''));");
        
        if ($btn) echo $form->input_('hidden','action','','',$btn,'',0,'','','','','','','');
        if ($id) echo $form->input_('hidden','id','','',$id,'',0,'','','','','','','');
        echo "<table style='width:100%;'>";
            echo "<tr><td>";
            echo $form -> titleandhelp($title,'','text-align:left');
            echo "</td><td>";
             if ($id)
             {
                $sql="SELECT name FROM ssubgroups WHERE id=".$id;
                $db->query($sql);
                if($db->getCount()>0)
                {
                    echo $form->input_('text','name','','',$db->getValue(),'width:350px;float:left;',0,'','','','','','','');
                }
                
             }
             else
             {
                echo $form->input_('text','name','','',$subgroup,'width:350px;float:left;',0,'','','','','','','');
             }
            
            echo "</td></tr>";
            echo "<tr><td colspan='2' align='center'><br />";
            echo $form->input_('submit', $btn, $btn,'','Сохранить','',0,'','','','','','','');
            echo "</td></tr>";
        echo "</table>";
        echo $form->forme();
        ?>
    </td>
  </tr>