
<?php
$page->setTitle('О компании');
  $page -> addScript("js/_animateNo1.js");
?>
<div class="margin_auto width4size header_h">
        <div class="body-margin">
        <div class="more-margin">
            <h1>О компании</h1>
            <div class="title_text mar_top_30">ООО&nbsp;«Высший сорт» — крупная дистрибьюторская компания в сфере продуктов питания,<br>охватывающая территорию Восточной Украины.</div>
				<div class="about_block float_left">
					<div class="page_text  mar_top_30 ">За последние десять лет непрерывного роста и развития, компания добилась значительных результатов — стала эксклюзивным представителем <a href="/bmk">Безлюдовского&nbsp;мясокомбината&nbsp;(БМК)</a> на территории Донецкой, Луганской и Днепропетровской областей. А с недавнего времени официальным партнером ООО «Высший сорт» стал <a href="/mmk">Марьянский&nbsp;мясокомбинат&nbsp;(ММК).</a></div>
					<div class="clear_both"></div>
					<div class="mar_top_40 page_text">
							<img class="float_left " src="/img/fsize1/bmk_acomp.png" alt="bmk" />	
								<div class="acomp_bmk_block">
										<a class="arial_12_18  float_left mar_left_10 "href="/bmk">Безлюдовский<br/>мясокомбинат (БМК)</a>
								</div>
							<img class="float_left mar_left_35" src="/img/fsize1/mmk_acomp.png" alt="bmk" />	
								<div class="acomp_bmk_block">
										<a class="arial_12_18  float_left mar_left_20 "href="/mmk">Марьянский<br/>мясокомбинат (ММК)</a>
								</div>
								
							<div class="clear_both"></div>
						<div class="page_text mar_top_30   ">В своем арсенале компания имеет три собственных логистических центра, солидный автопарк (автомобили грузоподъемностью от 700 до 5000&nbsp;кг), достаточное количество профессионального холодильного оборудования для обработки до 40&nbsp;000&nbsp;кг продукции 
																в сутки (по Донецкой, Луганской и Днепропетровской областям).</div>

						<div class="mar_top_50 color_gray">
						<img class="float_left " src="/img/fsize1/fura_acomp.png" alt="bmk" />	
						<div class="acomp_block_p">
								<p class="arial_12_18  float_left mar_left_10 ">Автомобили<br/>грузоподъемностью<br/>от 700 до 5000&nbsp;кг</p>
						</div>	
						
						<img class="float_left mar_left_20" src="/img/fsize1/holod_acomp.png" alt="bmk" />	
						
						<div class="acomp_block_p">
								<p class="arial_12_18  float_left  mar_left_10">Профессиональное<br/>холодильное <br/>оборудование</p>
						</div>	
						</div>
							<div class="clear_both"></div>
						<div class="page_text mar_top_30   ">Активно развивается фирменная торговая сеть ВС-МАРКЕТ™. Кроме этого, теперь у покупателей есть возможность приобрести высококачественную продукцию не выходя из дома или офиса, воспользовавшись новым сервисом компании — <br/><a href="/kkz">«корпоративно-коллективный заказ».</a></div>
					
						<div class="mar_top_40">
							<div class="page_text ">
								<img class="float_left " src="/img/fsize1/box_acomp.png" alt="bmk" />	
								<div class="acomp_foot_block width_resize_acomp_block">
									<a class="arial_12_18  float_left  "href="/kkz">Корпоративно –<br/>коллективный заказ</a>
								</div>
								<img class="float_left mar_left_10 mar_top_10" src="/img/fsize1/mag_acomp.png" alt="bmk"/>	
								
								<div class="acomp_foot_block">
										<a class="arial_12_18  float_left mar_left_10 "href="/customers">Фирменная <br/>торговая сеть<br/>«Высший сорт»</a>
								</div>
								
							</div>
						</div>
						
				</div> 				
					</div>
				<div class="float_right block_right_acomp">
				<div class="map_acomp"><img src="/img/fsize1/map_acomp.png" alt="license img"/></div>
				<div class="text_and_bg_acomp">Миссия компании:<br>«Донести все лучшее от производителей потребителям».</div>
				<div class="page_text  mar_top_50 ">Одновременно с существующей деятельностью компания «Высший&nbsp;сорт» развивает и новые направления. В ближайшем будущем планируется расширение ассортимента предлагаемых групп товаров (добавление молочной продукции, сыров), а также начало собственного производства колбасных изделий и покрытие новых территорий сбыта.</div>
				</div>	
			
		<div class="clear_both"></div>	
<div class="delim-sh mar_top_40"></div>


				<ul class="uderfooter  ">
                <li>
                    <div class="uderfooter_cust-li5-img"></div>
                    <div class="underfooter-title">
                        <a href="/assortment/full/">Ассортимент</a>
                        <br /><br />
                      Торговый дом «Высший сорт» предлагает широкий выбор высококачественных колбасных изделий из отборного сырья от лучших производителей.
                    </div>
                </li>
                <li class="left ">
                    <div class="uderfooter_cust-li2-img"></div>
                    <div class="underfooter-title">
                        <a href="/customers">Клиентам</a>
                        <br /><br />
                    Клиенты компании «Высший сорт», становится представителями крупной торговой сети и получают возможность развития собственного бизнеса на льготных условиях.
                   </div>
                </li>
                <li class="left ">
                    <div class="uderfooter_cust-li3-img"></div>
                    <div class="underfooter-title">
                        <a href="/partners">Партнерам</a>
                        <br /><br />
                     Ознакомить с действующими специальными предложениями и дисконтной программой. Ознакомить с действующими специальными предложениями и дисконтной программой. 
                    </div>
                </li>
                <li class="left ">
                    <div class="uderfooter_cust-li4-img"></div>
                    <div class="underfooter-title">
                        <a href="/career">Карьера</a>
                        <br /><br />
                     Приглашаем на конкурсной основе новых сотрудников, желающих работать в успешной компании и профессиональном коллективе.
             </div>
                </li>
             </ul>
</div>
</div>
</div>