<?php

$page->addScript('http://api-maps.yandex.ru/2.0/?load=package.standard&mode=debug&lang=ru-RU','js/map.js');
?>
<div class="margin_auto width4size header_h">
        <div class="body-margin">
        <div class="more-margin">
            <h1>Контактная информация</h1>
            <div class="contacts">
                <div class="f-l contacts-left-block">
                <div class="f-l contacts-title">
                    Центральный офис:
                </div>
                <div class="f-l">
                    <div class='on-map' id="mapone">На карте</div>
                </div>
                <div class="clear_both"></div>
                <div class="contacts-gray">
                    Индекс: <span class="contacts-else">86106</span>
                </div>
                <div class="contacts-gray">
                    Адрес: <span class="contacts-else">г. Макеевка, ул. Депутатская, 19 г.</span>
                </div>
                <div class="contacts-gray">
                    Телефон: <span class="contacts-else">(050) 474-33-83, (062) 341-16-91, (099) 22-64-778</span>
                </div>
                <div class="contacts-gray">
                    Email: <span class="contacts-else">info@vsort.com.ua</span>
                </div>
                
                <!-- -->
                
                 <div class="f-l contacts-title contacts-mezh">
                    Юридический адрес:
                </div>
                <div class="f-l contacts-mezh">
                    <div class='on-map' id="maptwo">На карте</div>
                </div>
                <div class="clear_both"></div>
                <div class="contacts-gray">
                    Индекс: <span class="contacts-else">86141</span>
                </div>
                <div class="contacts-gray">
                    Адрес: <span class="contacts-else">г. Макеевка, ул. Скнарева, 50А</span>
                </div>
                <div class="contacts-gray">
                    Телефон: <span class="contacts-else">(062) 341-16-91</span>
                </div>
                <div class="contacts-gray">
                    Email: <span class="contacts-else">info@vsort.com.ua</span>
                </div>
                 <!-- -->
                
                 <div class="f-l contacts-title contacts-mezh">
                    Луганский филиал ООО «Высший сорт»:
                </div>
                <div class="f-l contacts-mezh">
                    <div class='on-map' id="mapthree">На карте</div>
                </div>
                <div class="clear_both"></div>
                <div class="contacts-gray">
                    Индекс: <span class="contacts-else">91007</span>
                </div>
                <div class="contacts-gray">
                    Адрес: <span class="contacts-else">г. Луганск, ул. Лутугинская, 95Г</span>
                </div>
                <div class="contacts-gray">
                    Телефон: <span class="contacts-else">(099) 22-64-778</span>
                </div>
                <!--<div class="contacts-gray">
                    Email: <span class="contacts-else">vishiy@mail.ru</span>
                </div>-->
                 <!-- -->
                
                 <div class="f-l contacts-title contacts-mezh">
                     Днепропетровский партнер(филиал)
                     <br />ООО «Доминатор»:
                </div>
                <div class="f-l contacts-mezh">
                    <div class='on-map' id="mapfour">На карте</div>
                </div>
                <div class="clear_both"></div>
                <div class="contacts-gray">
                    Адрес: <span class="contacts-else">г. Днепропетровск, ул. Журналистов, 13</span>
                </div>
                    <div class="clear_both"></div>
                <div class="contacts-gray">
                    Телефон: <span class="contacts-else">(050) 342-05-02, (050) 106-20-48</span>
                </div>
                    <div class="f-l contacts-title contacts-mezh">
                       Представители завода
                    </div>
                    <div class="clear_both"></div>
                <div class="f-l contacts-title contacts-mezh">
                    ТОВ «Премиум» ТД «БМК»
                </div>
                <div class="clear_both"></div>
                <div class="contacts-gray f-l contacts-mezh">
                    Адрес: <span class="contacts-else">г. Кривой Рог, ул. Окружная, 3-К</span>
                </div>
                    <div class="f-l contacts-mezh">
                        <div class='on-map' id="mapfive">На карте</div>
                    </div>
                    <div class="clear_both"></div>
                <div class="contacts-gray ">
                    Телефон: <span class="contacts-else">(050) 409-52-55, (067) 539-41-21</span>
                </div>
                <!-- -->
                <div class="clear_both"></div>
                <div class="contacts-gray f-l contacts-mezh">
                    Адрес: <span class="contacts-else">г. Никополь,  п-т Трубников, 14</span>
                </div>
                <div class="f-l contacts-mezh">
                    <div class='on-map' id="mapsix">На карте</div>
                </div>
                    <div class="clear_both"></div>
                <div class="contacts-gray ">
                    Телефон: <span class="contacts-else">(067) 618-28-98</span>
                </div>
                <!-- -->
                <div class="clear_both"></div>
                    <div class="clear_both"></div>
                <div class="contacts-gray f-l contacts-mezh">
                    Адрес: <span class="contacts-else">г. Запорожье, ул. Трубников, 13</span>
                </div>
                <div class="f-l contacts-mezh">
                    <div class='on-map' id="mapseven">На карте</div>
                </div>
                 <div class="clear_both"></div>
                <div class="contacts-gray ">
                    Телефон: <span class="contacts-else">(067) 539-31-23</span>
                </div>
                <!-- -->
                <div class="clear_both"></div>
                <div class="contacts-gray f-l contacts-mezh">
                    Адрес: <span class="contacts-else">г. Симферополь,<br />ул. Генерала Васильева, 44-B</span>
                </div>
                <div class="f-l contacts-mezh">
                    <div class='on-map' id="mapeight">На карте</div>
                </div>
                    <div class="clear_both"></div>
                <div class="contacts-gray ">
                    Телефон: <span class="contacts-else">(067) 539-31-15</span>
                </div>


                </div>
                
                <div class="f-r contacts-right-block">
                    <div  style="width:100%;">
                        <div id="map"></div>
                    </div>
                </div>
                
            </div>
      </div>
      <div class="clear_both"></div>
      <div class="cont-after-all"></div>
              <div class="clear_both"></div>
            <div class="delim-sh"></div>
             <div class="clear_both"></div>
             
             <div>
           <ul class="uderfooter  ">
                <li>
                    <div class="uderfooter_cust-li5-img"></div>
                    <div class="underfooter-title">
                        <a href="/assortment/full/">Ассортимент</a>
                        <br /><br />
                      Торговый дом «Высший сорт» предлагает широкий выбор высококачественных колбасных изделий из отборного сырья от лучших производителей.
                    </div>
                </li>
                <li class="left mar_top_20">
                    <div class="uderfooter_cust-li2-img"></div>
                    <div class="underfooter-title">
                        <a href="/customers">Клиентам</a>
                        <br /><br />
                    Клиенты компании «Высший сорт», становится представителями крупной торговой сети и получают возможность развития собственного бизнеса на льготных условиях.
                   </div>
                </li>
                <li class="left mar_top_20">
                    <div class="uderfooter_cust-li3-img"></div>
                    <div class="underfooter-title">
                        <a href="/partners">Партнерам</a>
                        <br /><br />
                     Ознакомить с действующими специальными предложениями и дисконтной программой. Ознакомить с действующими специальными предложениями и дисконтной программой. 
                    </div>
                </li>
                <li class="left mar_top_20">
                    <div class="uderfooter_cust-li4-img"></div>
                    <div class="underfooter-title">
                        <a href="/career">Карьера</a>
                        <br /><br />
                     Приглашаем на конкурсной основе новых сотрудников, желающих работать в успешной компании и профессиональном коллективе.
             </div>
                </li>
             </ul>
             </div>
        </div>
        
</div>