
<?php
$page->setTitle('Клиентам');
?>
<?php 
$page->addScript('http://api-maps.yandex.ru/2.0/?load=package.standard&mode=debug&lang=ru-RU','js/map.js');
?>
<div class="margin_auto width4size header_h">
        <div class="body-margin">
        <div class="more-margin">
            <h1>Клиентам</h1>
            <div class="title_text mar_top_30">Компания «Высший&nbsp;сорт» работает на рынке мясных и колбасных изделий с 2003&nbsp;г. </div>
							
						 <div class="page_text   mar_top_20 mar_bot_35">За годы работы, нашими клиентами стали тысячи предпринимателей, с которыми мы продолжаем и дальше успешно развивать бизнес. Не смотря на жесткую конкурентную среду и изобилие мясокомбинатов на рынке, совместными усилиями были приняты и внедрены единые принципы работы с нашими потребителями: </div>
		
					
			 <div class="clear_both"></div>
			 
			 
			<div class="w_25 float_left mar_left_60">
			<span class="custom_numb_big float_left">1</span>
			<div class="after_custom_n_b">Максимально <br/>безопасная доставка <br/>и хранение продукции.</div>
			</div>
			<div class="w_25 float_left mar_left_50">
			<span class="custom_numb_big float_left">2</span>
			<div class="after_custom_n_b">Всегда свежий  <br/>продукт на местах <br/>реализации. </div>
			</div>
			<div class="w_30 float_left mar_left_40">
			<span class="custom_numb_big float_left">3</span>
			<div class="after_custom_n_b">Все только вкусное  <br/>и качественное от лучших <br/>производителей.</div>
			</div>
			  <div class="clear_both"></div>
			  
			 <div class="page_text   w_50 float_left mar_top_45">В 2012&nbsp;году, число приверженцев продукции которую поставляет компания «Высший Сорт» возросло на 47%, что составило 900&nbsp;000 потребителей.</div>
			 <div class="page_text   w_48 float_right mar_top_45">К декабрю 2014&nbsp;года мы планируем расширить фирменную сеть до 500 магазинов на территории Луганской, Донецкой и Днепропетровской областей. </div>
			
			 <div class="clear_both"></div>
			<div class="page_text   mar_top_25">Вы можете стать представителем крупной сети, работающей по революционно новым технологиям в колбасном бизнесе и под яркой, запоминающей торговой маркой «ВС-МАРКЕТ». </div>
			
<div class=" title_text   f_18  mar_top_30 ">А главное — Вы получаете:</div>

		
		</div>
		</div>
		</div>
		
		
<div class="clear_both"></div>
		<div class="center_img">	<div class="center_img2">
		<div class="text_top_custom ">Готовый бизнес с минимальными вложениями и риском.<div class="text_top_right_custom float_left">Льготные условия работы.</div></div>
		
		<div class="text_right_1_custom float_right mar_left_20">Обеспечение партнёра <br/>проверенной временем  <br/>системой ведения бизнеса, <br/>а также предоставление <br/>консультаций специалистов  <br/>нашей компании по всем  <br/>бизнес-вопросам.</div>

		
		<div class="text_left_1_custom">Рекламная поддержка <br/>для сетимагазинов <br/>ВС-МАРКЕТ ™, размещение<br/> на сайте и в рекламных<br/> материалах полной<br/> информации о партнерских <br/>магазинах с указанием <br/>адресов и телефонов.</div>
		<div class="text_right_1_custom  mar_top_0 float_right pos_rel">Помощь в формировании  <br/>сбалансированного  <br/>ассортимента для нового <br/> магазина с учётом сезона <br/> и особенностей Вашего  <br/>региона и предоставление  <br/>ранней доставки. </div>
		
		<div class="text_left_2_custom">Предоставление  <br/>обучающих программ для <br/>продавцов-консультантов. </div>
		<div class="text_left_2_custom">Предоставление рекламных  <br/>материалов, элементов <br/>фирменного стиля. </div>
		<div class="text_bot_1_custom float_left">Помощь в разработке и проведении  <br/>рекламных мероприятий индивидуально  <br/>для каждого партнёрского магазина. </div>
		<div class="text_bot_2_custom float_left">Единые розничные цены во всей <br/> сети  и предоставление единой <br/>дисконтной  программы «ВС-МАРКЕТ». </div>
		</div>
		</div>
<div class="margin_auto width4size header_h">
        <div class="body-margin">
      <div class="clear_both"></div>
   <div class="more-margin">
   <div class=" title_text   f_18  mar_top_40">Требования к расположению и внешнему виду фирменного магазина ВС-МАРКЕТ™.</div>
	<div class="w_48 mar_right_5 float_left">
						<div class="page_text   mar_top_40">Оптимальная площадь магазина от 20 до 50&nbsp;кв.м. Внешний вид магазина должен быть выполнен в соответствии со стандартами. </div>
						<div class="page_text   mar_top_30">Предпочтение отдаётся областным центрам и городам с населением от 200&nbsp;000&nbsp;человек.</div>
					
			</div>
			<div class="w_47  float_right">
						<div class="page_text   mar_top_40">В фирменном магазине должна быть представлена в основном продукция компании «Высший&nbsp;Сорт».</div>
						<div class="page_text   mar_top_30"><span class="red_text_bold">Важно!</span> С каждым партнёром мы подписываем договор на эксклюзивное право развития сети в определённом регионе.</div>
					
			</div>
			  <div class="clear_both"></div>
			  <div class="bot_text_bg mar_top_40">По вопросам сотрудничества и дополнительной информации обращаться по тел : +38 (099) 231-88-11</div>
			 <!-- <div class=" title_text   f_18  mar_top_40">Фирменная сеть</div>
			<div class="page_text   mar_top_7">Независимо от географии расположения магазины фирменной сети «Высший сорт» предлагают всегда свежую продукцию, комфортные цены, отборный ассортимент, приятную атмосферу и высокую культуру обслуживания потребителей.</div>
			
			
			
					
			 
                <div class="w835">
                    <div  style="width:100%;">
                        <div id="map"></div>
                    </div>
                </div>
				-->
				  <div class="clear_both"></div>
				  <div class="delim-sh"></div>
				<ul class="uderfooter mar_top_40 ">
                <li class="">
                    <div class="uderfooter_cust-li1-img"></div>
                    <div class="underfooter-title">
                        <a href="/about">О компании</a>
                        <br /><br />
                        «Высший сорт» - успешная компания с многолетним опытом в сфере дистрибуции продуктов питания на территории Восточной Украины.
                    </div>
                </li>
                <li class="left">
                     <div class="uderfooter_cust-li5-img"></div>
                    <div class="underfooter-title">
                        <a href="/assortment/full/">Ассортимент</a>
                        <br /><br />
                      Торговый дом «Высший сорт» предлагает широкий выбор высококачественных колбасных изделий из отборного сырья от лучших производителей.
                    </div>
                </li>
                <li class="left ">
                    <div class="uderfooter_cust-li3-img"></div>
                    <div class="underfooter-title">
                        <a href="/partners">Партнерам</a>
                        <br /><br />
                     Ознакомить с действующими специальными предложениями и дисконтной программой. Ознакомить с действующими специальными предложениями и дисконтной программой. 
                    </div>
                </li>
                <li class="left ">
                    <div class="uderfooter_cust-li4-img"></div>
                    <div class="underfooter-title">
                        <a href="/career">Карьера</a>
                        <br /><br />
                    Приглашаем на конкурсной основе новых сотрудников, желающих работать в успешной компании и профессиональном коллективе.
                    </div>
                </li>
             </ul>
			
</div>
</div>
</div>