<?php
$page->setTitle('ВЫСШИЙ СОРТ');
$page -> addScript("js/_animatemain.js");
$page -> addScript("js/main_prohod.js"); 
?>
<div class="w1000 mar_bot_40">
    <div style="position:relative;">
        <div id="bg_canvas" class="bg_img_main_1000 "></div>
        <div id="replay"><div class id="replay_bt"></div></div>
        <!--div id="replay "></div-->
        <div id="fly">

            <div id="stats" style="color: red;position: absolute;z-index: 100;width:120px"></div>
            <div id="gradient"></div>
            <canvas id="canvas">Не работает</canvas>
        </div>
    </div>
    <div class="box_hover_opacity" id="opacity_box"></div>
    <div class="box_hover_opacity" id="opacity_box2" ></div>
    <div class="boxgrid boxgrid2 1img"  style="z-index:100;">
        <div class="main_load main_img_1 "></div>

        <div class="cover "></div>
        <div class="view view-third">
            <div class="mask">
                <h2><a class=" href_main_cube  href_main_cube_1 " href="/product/more/id/000000045/from/kkz" > Новинка</a></h2>
                <p class="main_cub_text">Брауншвейгская 1с<br/>Безлюдовский<br/>мясокомбинат</p>

            </div>
        </div>

    </div>
    <div class="boxgrid  boxgrid1 2img"  >
        <div class="cover "></div>
        <div class="main_load main_img_2 "></div>
        <div class="view view-third">
            <div class="mask">
                <h2><a class=" href_main_cube href_main_cube_2" href="/about"> Клиентам</a></h2>
                <p class="main_cub_text">Оперативность<br/>доставки, свежесть<br/>продукции,<br/>гарантия качества</p>

            </div>
        </div>

    </div>

    <a class="pointer" href="/index">
        <div class="boxgrid boxgrid2 3img"   >
            <div class="main_load main_img_3 "></div>


        </div>
    </a>

    <div class="boxgrid boxgrid3 4img">
        <div class="main_load main_img_4 "></div>
        <div class="cover "></div>
        <div class="view view-third">
            <div class="mask">
                <h2><a class=" href_main_cube  href_main_cube_4" href="/bmk">«БМК»</a></h2>
                <p class="main_cub_text">Высшее качество,<br/>незабываемый вкус,<br/>широкий ассортимент</p>

            </div>
        </div>
    </div>






    <div class="boxgrid boxgrid4 5img"   >

        <div class="cover "></div>
        <div class="main_load main_img_5 "></div>
        <div class="view view-third">
            <div class="mask">
                <h2><a class=" href_main_cube  href_main_cube_5" href="/about">О&nbsp;Компании</a></h2>
                <p class="main_cub_text">Донести все лучшее<br/>от производителей<br/>потребителям</p>
            </div>
        </div>
    </div>
    <div class="boxgrid boxgrid2 6img"  style="z-index:100;" >
        <div class="main_load main_img_6 "></div>
        <div class="cover "></div>
        <div class="view view-third">
            <div class="mask">
                <h2><a class=" href_main_cube  href_main_cube_6" href="/kkz" >Доставка</a></h2>
                <p class="main_cub_text">Доставка осуществляется на всей территории Донецка и Макеевки.</p>
            </div>
        </div>

    </div>
    <div class="boxgrid boxgrid2 7img"  style="z-index:1000;" >
        <div class="main_load main_img_7 "></div>
        <div class="cover "></div>
        <div class="view view-third">
            <div class="mask">
                <h2><a class=" href_main_cube href_main_cube_7 " href="/kkz">«ККЗ»</a></h2>
                <p class="main_cub_text">Корпоративно-коллективный заказ – это новый сервис компании «Высший сорт»</p>
            </div>
        </div>
    </div>

    <div class="boxgrid boxgrid5 8img" style="z-index:1000">
        <div class="main_load main_img_8 "></div>

        <div class="cover "></div>
        <div class="view view-third">
            <div class="mask">
                <h2><a class=" href_main_cube  href_main_cube_8" href="/mmk">«ММК»</a></h2>
                <p class="main_cub_text">Семейные традиции<br/>и современное<br/>производство</p>
            </div>
        </div>
    </div>


    <div class="boxgrid boxgrid6 9img">
        <div class="main_load main_img_9 "></div>

        <div class="cover "></div>
        <div class="view view-third">
            <div class="mask">
                <h2><a class=" href_main_cube  href_main_cube_9" href="/partners">Партнерам</a></h2>
                <p class="main_cub_text">Сотрудничество<br/>с нами — успех<br/>вашего производства</p>
            </div>
        </div>

    </div>

    <div class="boxgrid boxgrid7 10img">
        <div class="main_load main_img_10 "></div>

        <div id="procent_load"></div>
        <div id="replay_bt_after"></div>

    </div>

    <div class="boxgrid boxgrid8 11img" style="z-index:10000">
        <div class="main_load main_img_11 "></div>

        <div class="cover "></div>
        <div class="view view-third">
            <div class="mask">
                <h2><a class=" href_main_cube  href_main_cube_11" href="/career">Карьера</a></h2>
                <p class="main_cub_text">Сотрудники — самый<br/>ценный ресурс<br/>нашей компании</p>
            </div>
        </div>

    </div>

    <div class="boxgrid boxgrid2 12img"  style="z-index:1000;" >
        <div class="main_load main_img_12 "></div>
        <div class="cover "></div>
        <div class="view view-third">
            <div class="mask">
                <h2><a class=" href_main_cube  href_main_cube_12" href="/product/more/id/000000091/from/kkz" > Новинка</a></h2>
                <p class="main_cub_text">Бутербродная 2с<br/>Марьянский <br/>мясокомбинат</p>

            </div>
        </div>

    </div>



</div>
<div class="margin_auto width4size header_h">
<div class="body-margin">
<div class="more-margin">

<div class="title_text  mar_bot_50 ">Торговый дом «Высший сорт» является прогрессивной и надежной компанией<br>в сфере торговли колбасными изделиями уже более 10-ти лет.</div>


<div class="  text_main_block float_left">
    <div class="page_text">Высокий профессионализм , добросовестное отношение к клиентам, любовь к своему делу и высокие показатели деятельности позволили стать эксклюзивным представителем <a class="href_page" href="/bmk">Безлюдовского мясокомбината (БМК)</a> на территории Донецкой, Луганской и Днепропетровской областей. Также с недавнего времени  официальным партнером ООО&nbsp;«Высший&nbsp;сорт» стал <a class="href_page" href="/mmk">Марьянский мясокомбинат (ММК). </a></div>
</div>
<div class="main_right_bef float_right">
    <div class="main_right page_text">
        <img class="  mar_left_10" src="/img/fsize1/bmk_main.png" alt="bmk" />
        <a class="href_page    "href="/bmk">Безлюдовский<br/>мясокомбинат<br/>(БМК)</a>
        <img class="  mar_left_20" src="/img/fsize1/mmk_main.png" alt="mmk" />
        <a class="href_page    "href="/mmk">Марьянский<br/>мясокомбинат<br/>(ММК)</a>
    </div>
</div>
<div class="clear_both"></div>

<ul class="mar_top_50">
<li class="li_main_first float_left color_black"><div class="underfooter-title">
        <a href="/about">О компании</a>
        <br /><br />
        За прошедшие 10 лет роста и развития, компания добилась значительных  результатов.
    </div></li>
<li class="float_left"><div class="main_img_acomp"></li>
<li class="li_main_sec float_left color_black mar_left_10"><div class="underfooter-title">
        <a href="/customers">Клиентам</a>
        <br /><br />
        За годы работы нашими клиентами стали сотни частных предпринимателей и магазинов.
    </div></li>
<li class="float_left"><div class="main_img_client"></li>

<li class=" li_main_th float_left color_black"><div class="underfooter-title">
        <a href="/kkz">Корпоративно-коллективный заказ</a>
        <br /><br />
        <div class="li_main_th_1 float_left">В ассортименте колбасных изделий особое место сотни частных предпринимателей занимают копченые колбасы.</div>
    </div>
    <div class="main_img_kkz float_right">
</li>


<div class="clear_both"></div>
<div class="title_text mar_top_80 mar_bot_20 f_24">Ассортимент</div>


<!--div class="title_text mar_top_80 mar_bot_20 f_24">Корпоративно-коллективный заказ (ККЗ)</div>
<div class="float_left w_47 page_text">Корпоративно- коллективный заказ  (ККЗ) – это прекрасная возможность для вас, ваших коллег и друзей получать самые свежие и любимые вами колбасы, не выходя из офиса или дома.</div>
<div class="float_right w_47 page_text">Ваш заказ будет доставлен вам в установленный день и согласованное время. В зависимости от объема заказа действуют <a href="#">специальные условия доставки.</a></div-->



<div class="clear_both"></div>




   <?php 
                $sql="SELECT * FROM goods WHERE hot_products=1 ".$sql_output;
                $db->query($sql);
				
                if($db->getCount()>0)
                {
                    $arrpro=$db->getArray();
                    echo "<ul class='ass-all'>";
                    foreach($arrpro as $arrproindex=>$arrproval)
                    {
					
							
									if(($arrproindex+1)%4==0)
									{
										echo "<li class='no-margin-r'>";
									}
									else  echo "<li>";
									if(!empty($arrproval['photo']))
									{
										$photo=str_replace('.','',$arrproval['photo']);
										$photo=str_replace('-','_',$photo);
										
										if(file_exists($root."/img/products/fsize1/".$photo."_ass.jpg"))
										{
											echo "<div>".$new." ".$hot."<a href='/product/more/id/".$arrproval['id']."/from/assortiment'><img src='../img/products/fsize1/".$photo."_ass.jpg' /></a></div>";
											echo "<div class='clear_both'></div>"; 
										}
										else
										{
											 echo "<div>".$new." ".$hot."<a href='/product/more/id/".$arrproval['id']."/from/assortiment'><img src='../img/products/fsize1/good-empty_ass.png' /></a></div>";
											 echo "<div class='clear_both'></div>";
										}
									}
									else
									{
										 echo "<div>".$new." ".$hot."<a href='/product/more/id/".$arrproval['id']."/from/assortiment'><img src='../img/products/fsize1/good-empty_ass.png' /></a></div>";
										 echo "<div class='clear_both'></div>";
									}
									//echo $returnphoto;
								   // echo  $prd->kkzphoto($arrproval['photo'],$arrproval['id']);
										 
									echo "<a class='name' href='/product/more/id/".$arrproval['id']."/from/assortiment'>".$arrproval['name']."</a>";
									echo "<div class='after-name'></div>";
									echo $prd->getmanufname($arrproval['idmanufacturers']);
									$base_ed=$prd->getpricefor($arrproval['id_base_ed_iz']);
									if(!empty($base_ed))
									{
											echo "<br />";
											echo '<div class="other">Цена за '. $base_ed.': '. $prd->priceofbaseediz($arrproval['id']).' грн</div>';
									}
									if(!empty($arrproval['weight']))
									{
										 echo "<div class='other f-l'>Вес : ".$arrproval['weight']."</div>";
									}
								   
									echo "</li>";
						
					
                    }
                    echo "</ul>";
					
					  echo '<div class=" button_all_god  " ><a class="all_product " style="padding-left:31px;" href="/assortment/full/cat/000000003/firm/000000001">Показать&nbsp;еще</a>';
          
                }
                ?>

<br/>
<div class="clear_both"></div>
</div>
</div>
</div>